name: Build & Publish TEST pypi

on: workflow_dispatch

jobs:

  build_binary_native:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
       os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-15]
       pyver: [cp39, cp310, cp311, cp312, cp313, cp314, cp314t]
       exclude:
         - os: windows-11-arm
           pyver: cp39


    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ matrix.os }} ${{ matrix.pyver }}
        uses: pypa/cibuildwheel@v3.1
        env:
          CIBW_BUILD: ${{ matrix.pyver }}-*
          CIBW_BEFORE_BUILD: python -c "import shutil ; shutil.copyfile('tools/setup-pypi.cfg','setup.apsw')"
          CIBW_TEST_COMMAND: python -m apsw.tests -v
          APSW_HEAVY_DURATION: 2

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.pyver }}
          path: ./wheelhouse/*.whl

  build_source:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create source dist
      run: python setup.py sdist --for-pypi

    - uses: actions/upload-artifact@v4
      with:
        name: dist-source
        path: ./dist/*

  pypi_publish:
    needs: [build_source, build_binary_native]
    runs-on: ubuntu-latest
    permissions:
        id-token: write

    steps:
    - name: Stage wheels
      uses: actions/download-artifact@v4
      with:
        pattern: dist-*
        merge-multiple: true
        path: dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
       repository-url: https://test.pypi.org/legacy/

